apiVersion: v1
kind: Pod # This is the type of Kubernetes resource we are creating
metadata:
  name: bb-app1-pod # This is the name of the Pod
  labels:
    app: bb-app1 # This is a label for the Pod
spec:
  containers:
  - name: bb-app1-container # This is the name of the container
    image: nginx:1.7.9 # This is the image we are using for the container
    ports:
    - containerPort: 80 # This is the port the container will listen on