apiVersion: v1
kind: Service
metadata:
  name: bb-app1-service
spec:    
  selector:
    app.kubernetes.io/name: bb-app1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 80
      nodePort: 30007